# -*- coding: utf-8 -*-
"""
Created on 2025-10-29 09:12:41
---------
@summary:
---------
@author: lucas
"""
import hashlib

from feapder import UpdateItem


class SpiderWebImgUrlItem(UpdateItem):
    """
    This class was generated by feapder
    command: feapder create -i spider_web_img_url 1
    """

    __table_name__ = "spider_web_img_url"
    __update_key__ = ["title", "tags"]

    def __init__(self, *args, **kwargs):
        self.uuid = hashlib.md5(f"{kwargs.get('website', '')}_{kwargs.get('url', '')}".encode('utf-8')).hexdigest()  # hash主键，由 website+url hash得到
        self.website = kwargs.get('website')  # 网站标题
        self.title = kwargs.get('title')  # 图片标题
        self.tags = kwargs.get('tags')  # 图片标签
        self.url = kwargs.get('url')  # 图片链接
        self.status = kwargs.get('status', 0)  # 下载状态 0:未下载 1:下载完成 -1:下载失败
        # self.created_at = kwargs.get('created_at')  # 创建时间
        # self.updated_at = kwargs.get('updated_at')  # 更新时间
        self.file = kwargs.get('file')  # 下载的文件地址
